name: finmamba
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pytorch=2.5.1
  - pytorch-cuda=12.4
  - torchaudio=2.5.1
  - torchvision=0.20.1
  - torchtriton=3.1.0
  - numpy
  - pip
  - pip:
      - accelerate==1.3.0
      - bitsandbytes==0.45.0
      - causal-conv1d==1.5.0.post8
      - datasets==3.2.0
      - einops==0.8.0
      - huggingface-hub==0.27.1
      - hydra-core==1.3.2
      - hydra-optuna-sweeper==1.2.0
      - mamba-ssm==2.2.4
      - matplotlib==3.10.0
      - omegaconf==2.3.0
      - optuna==2.10.1
      - pandas==2.2.3
      - peft==0.14.0
      - safetensors==0.5.2
      - scikit-learn==1.6.1
      - seaborn==0.13.2
      - tokenizers==0.21.0
      - tqdm==4.67.1
      - transformers==4.48.0
